itemDef 
{
	rect -105 -53 210 106 HORIZONTAL_ALIGN_CENTER VERTICAL_ALIGN_CENTER
	style WINDOW_STYLE_FILLED
	border 1
	bordercolor 0.498 0.859 1.000 .3
	forecolor 1 1 1 1
	backcolor 0 0 0 .6
	visible 	1
	decoration
}
itemDef
{
	rect		0 -36 1 1 HORIZONTAL_ALIGN_CENTER VERTICAL_ALIGN_CENTER
	origin		0 0
	text		"^5#^7promodUntitled v0.12.0.2"
	textscale	0.3
	textalign	ITEM_ALIGN_CENTER
	textstyle	ITEM_TEXTSTYLE_SHADOWED
	forecolor   0.498 0.859 1.000 .6
	visible 	1
	decoration 
}
itemDef
{
	rect		0 0 1 1 HORIZONTAL_ALIGN_CENTER VERTICAL_ALIGN_CENTER
	origin		0 0
	text		"MOD IN DEVELOPMENT!"
	textscale	0.5
	textalign	ITEM_ALIGN_CENTER
	textstyle	ITEM_TEXTSTYLE_SHADOWED
	forecolor   1.000 0.255 0.212 .6
	visible 	1
	decoration 
}

itemDef
{
	rect		0 5 1 1 HORIZONTAL_ALIGN_CENTER VERTICAL_ALIGN_CENTER
	origin		0 0
	text		"Project with source is available on gitHub.\nFeedback is very welcome."
	textfont	UI_FONT_CONSOLE
	textscale	0.19
	textalign	ITEM_ALIGN_CENTER
	textstyle	ITEM_TEXTSTYLE_SHADOWED
	forecolor   1 1 1 .6
	visible 	1
	decoration 
}
itemDef
{
	rect		0 45 1 1 HORIZONTAL_ALIGN_CENTER VERTICAL_ALIGN_CENTER
	origin		0 0
	text		"Github.com/MartinKogovsek/promodUntitled"
	textfont	UI_FONT_CONSOLE
	textscale	0.19
	textalign	ITEM_ALIGN_CENTER
	textstyle	ITEM_TEXTSTYLE_SHADOWED
	forecolor   1 1 1 .6
	visible 	1
	decoration 
}