//gradient top
itemDef
{
	style			WINDOW_STYLE_SHADER
	rect			0 0 854 150 HORIZONTAL_ALIGN_FULLSCREEN 0
	background		"gradient_fadein_t"
	forecolor		0.75 0.02 0.2 1
	visible			1
	decoration
}
//gradient bot
itemDef
{
	style			WINDOW_STYLE_SHADER
	rect			0 0 854 600 HORIZONTAL_ALIGN_FULLSCREEN 0
	background		"gradient_fadein_b"
	forecolor		0.75 0.02 0.2 1
	visible			1
	decoration
}
//black
itemDef
{
	style			WINDOW_STYLE_FILLED
	rect			0 0 854 854 HORIZONTAL_ALIGN_FULLSCREEN 0
	backcolor		0 0 0 0.9
	visible			1
	decoration
}