itemDef
{
	rect 			0 35 220 1 HORIZONTAL_ALIGN_LEFT VERTICAL_ALIGN_TOP
	style 			WINDOW_STYLE_FILLED
	backcolor 		0.4 0.8 1 1
	visible 		1
	decoration
}
itemDef
{
	rect            221 38 0 0 HORIZONTAL_ALIGN_LEFT VERTICAL_ALIGN_TOP
	style           WINDOW_STYLE_FILLED
	type            ITEM_TYPE_TEXT
	text            "promodUntitled"
	forecolor       0.4 0.8 1 1
	textscale       0.6
	textstyle	    ITEM_TEXTSTYLE_SHADOWED
	textalign       ITEM_ALIGN_RIGHT
	visible         1
	decoration
}