//title bg
itemDef
{
	style			WINDOW_STYLE_SHADER
	rect			-50 38 200 40 HORIZONTAL_ALIGN_FULLSCREEN 0
	background		"cp_title_bg"
	forecolor		0.75 0.02 0.2 0.8
	visible			1
	decoration
}
itemDef
{
	rect            110 60 0 0 HORIZONTAL_ALIGN_LEFT VERTICAL_ALIGN_TOP
	style           WINDOW_STYLE_FILLED
	type            ITEM_TYPE_TEXT
	text            "PROMOD"
	forecolor       0 0 0 0.6
	textscale       0.5
	textfont		UI_FONT_OBJECTIVE
	textstyle	    ITEM_TEXTSTYLE_NORMAL
	textalign       ITEM_ALIGN_RIGHT
	visible         1
	decoration
}
itemDef
{
	rect            160 80 0 0 HORIZONTAL_ALIGN_LEFT VERTICAL_ALIGN_TOP
	style           WINDOW_STYLE_FILLED
	type            ITEM_TYPE_TEXT
	text            "UNTITLED"
	forecolor       0 0 0 0.6
	textscale       0.5
	textfont		UI_FONT_OBJECTIVE
	textstyle	    ITEM_TEXTSTYLE_NORMAL
	textalign       ITEM_ALIGN_RIGHT
	visible         1
	decoration
}